name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish Blazor App
        run: dotnet publish DailyLiftApp/DailyLiftApp.Client/DailyLiftApp.Client.csproj -c Release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --project dailyliftapp-aa3e1 --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
